version: '3.8'

services:
  web-app:
    build: .
    container_name: node-app-container
    ports:
      - "80:3000"
    restart: always

  monitoring:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-data:/app/data
    restart: always

volumes:
  uptime-data:
